id: P009478
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:40:39.120365
source_metadata:
  id: bdr:W8LS16238
  title: གུ་རུ་སིདྡྷིའི་ལས་ཚོགས་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    ed2f8b3c8a6f41c2bc51a036200359c2:
      image_group_id: I8LS16240
      title: ''
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
